controllerPackage: io.swagger.petstore.controller
modelPackage:  io.swagger.petstore.model
swaggerUrl: openapi.yaml

exposedSpecOptions:
  useOriginalNotParsed: true

entityProcessors:
- json
- yaml
- xml

swaggerProcessors:
- io.swagger.petstore.utils.HandleAuthUrlProcessor

rootPath: /api