// Generated by Skyramp v1.3.13 on 2026-03-23 10:37:01.661855 -0700 PDT m=+413.806707709
// Command: skyramp generate contract rest http://localhost:8080/api/v3/pet/findByStatus \
// 		--api-schema /Users/archit/Projects/swagger-api/swagger-petstore/src/main/resources/openapi.yaml \
// 		--framework junit \
// 		--language java \
// 		--method GET \
// 		--output SkyrampPetFindByStatusContractTest.java \
// 		--output-dir /Users/archit/Projects/swagger-api/swagger-petstore/src/test/java/io/swagger/petstore/contract \
// 		--overwrite \
// 		--provider \
// 		--query-params status=available \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents
//
// Default package: Skyramp Docker test runner selects this class by short name (SkyrampPetFindByStatusContractTest).

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

import static dev.skyramp.api.Skyramp.asMap;
import static dev.skyramp.api.Skyramp.checkSchema;
import static dev.skyramp.api.Skyramp.checkStatusCode;
import static dev.skyramp.api.Skyramp.getBaseUrl;
import static dev.skyramp.api.Skyramp.getValue;
import dev.skyramp.api.SkyrampClient;
import dev.skyramp.exception.SkyrampException;
import dev.skyramp.model.RequestV2;

public final class SkyrampPetFindByStatusContractTest {
    // URL for test requests
    String URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

    // contract test for /api/v3/pet/findByStatus GET
    @Test
    public void testFindByStatusGet() throws SkyrampException {
        // Invocation of Skyramp Client
        var client = new SkyrampClient();
        // Definition of authentication header
        String token = System.getenv("SKYRAMP_TEST_TOKEN");
        Map<String, String> headers = Map.of();
        if (token != null && !token.isEmpty()) {
            headers = Map.of("Authorization", "Bearer " + token);
        }

        // Expected Response Body
        String expectedFindByStatusGetResponseBody = """
            [
                {
                    "category": {
                        "id": 1,
                        "name": "Dogs"
                    },
                    "id": 10,
                    "name": "doggie",
                    "photoUrls": [
                        "string"
                    ],
                    "status": "available",
                    "tags": [
                        {
                            "id": 0,
                            "name": "string"
                        }
                    ]
                }
            ]
        """;

        // Execute Request
        var findByStatusGetResponse = client.sendRequest(RequestV2.builder()
            .url(URL)
            .path("/api/v3/pet/findByStatus")
            .method("GET")
            .headers(headers)
            .queryParams(asMap("status", "available"))
            .build());

        // Generated Assertions
        assertTrue(checkStatusCode(findByStatusGetResponse, "200"));
        assertTrue(checkSchema(findByStatusGetResponse, expectedFindByStatusGetResponseBody));
        assertNotNull(getValue(findByStatusGetResponse, "0.category.id"));
        assertNotNull(getValue(findByStatusGetResponse, "0.category.name"));
        assertNotNull(getValue(findByStatusGetResponse, "0.id"));
    }
}
