name: Maven CI Pipeline

# Triggers the workflow on push or pull requests to the 'main' branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Also, allow manual triggering via workflow_dispatch
  workflow_dispatch:
    inputs:
      version:
        description: "New version for the pom.xml (e.g., 1.0.23-SNAPSHOT)"
        required: true
        default: "1.0.0-SNAPSHOT"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Replace the version in pom.xml with the updated version
      - name: Update version in pom.xml
        run: |
          echo "Updating POM version to ${{ github.event.inputs.version }}"
          sed -i 's/<version>.*<\/version>/<version>${{ github.event.inputs.version }}<\/version>/' pom.xml

      # Step 3: Cache Maven dependencies to speed up build times
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and package the project using Maven
      - name: Build and package with Maven
        run: mvn clean package
